---
- name: Get foreign erc type
  become_user: "{{ compose_service_user }}"
  shell: docker-compose run --rm --entrypoint "node scripts/initialChecks.js" bridge_affirmation
  args:
    chdir: "{{ bridge_path }}/oracle"
  register: ERCTYPE

- name: Set FOREIGN_ERC_TYPE variable
  set_fact:
    FOREIGN_ERC_TYPE: "{{ (ERCTYPE.stdout).foreignERC | default('') }}"

- name: Extend docker compose file
  set_fact:
    composefileoverride: "-f docker-compose-transfer.yml"
    compose_env_extend: "docker-compose-transfer.yml"
  when: ORACLE_BRIDGE_MODE == "ERC_TO_ERC" and FOREIGN_ERC_TYPE != "ERC677"

- name: Extend docker compose file for erc to native
  set_fact: 
    composefileoverride: "-f docker-compose-erc-native.yml"
    compose_env_extend: "docker-compose-erc-native.yml"
  when: ORACLE_BRIDGE_MODE == "ERC_TO_NATIVE"

- name: Write COMPOSE_FILE to the .env
  blockinfile:
    path: "{{ bridge_path }}/oracle/.env"
    marker: "## {mark} Extend docker-compose after ERC check"
    block: |
      COMPOSE_FILE={{ compose_env_extend }}
  when: compose_env_extend | default('', true) | trim != ''

- name: Install .key config
  template:
    src: key.j2
    dest: "{{ keyfile_path }}"
    owner: root
    group: root
    mode: 0600
