---
version: '2.4'
services:
  monitor:
    image: poanetwork/tokenbridge-monitor:latest
    env_file: ./.env
    environment: 
      - NODE_ENV=production
    volumes:
      - ./responses:/mono/monitor/responses
    restart: unless-stopped
    entrypoint: "yarn start"
    networks:
      - net_rpc_external
networks:
  net_rpc_external:
    external:
      name: ${BRIDGE_EXTERNAL_NETWORK}
