version: '2.4'
services:
  parity_mainnet:
    image: parity/parity:v2.5.13-stable
    command:
      - "--no-download"
      - "--mode=active"
      - "--auto-update=none"
      - "--base-path=/data"
      - "--no-hardware-wallets"
      - "--port=30303"
      - "--max-peers=25"
      - "--max-pending-peers=10"
      - "--jsonrpc-allow-missing-blocks"
      - "--jsonrpc-no-keep-alive"
      - "--jsonrpc-interface=all"
      - "--jsonrpc-port=8545"
      - "--jsonrpc-apis=safe"
      - "--jsonrpc-cors=all"
      - "--ws-interface=all"
      - "--ws-port=8546"
      - "--ws-apis=safe"
      - "--ws-origins=all"
      - "--no-ipc"
      - "--no-secretstore"
      - "--no-secretstore-http"
      - "--no-persistent-txqueue"
      - "--no-color"
      - "--tracing=off"
      - "--pruning=fast"
      - "--db-compaction=ssd"
      - "--cache-size=2048"
      - "--no-periodic-snapshot"
    volumes:
      - type: bind
        source: /parity-main/
        target: /data
    restart: unless-stopped
    mem_limit: 8G
    mem_reservation: 16M
    oom_kill_disable: true
    stop_grace_period: 1m
    ports:
      - "8545:8545"
    networks:
      - net_rpc_external
      - dai_net_rpc_external
  parity_ewc:
    image: parity/parity:v2.5.13-stable
    command:
      - "--chain=/data/EnergyWebChain.json"
      - "--no-download"
      - "--mode=active"
      - "--auto-update=none"
      - "--base-path=/data"
      - "--no-hardware-wallets"
      - "--port=30303"
      - "--min-peers=16"
      - "--max-peers=24"
      - "--max-pending-peers=32"
      - "--jsonrpc-allow-missing-blocks"
      - "--jsonrpc-no-keep-alive"
      - "--jsonrpc-interface=all"
      - "--jsonrpc-port=8545"
      - "--jsonrpc-apis=safe"
      - "--jsonrpc-cors=all"
      - "--ws-interface=all"
      - "--ws-port=8546"
      - "--ws-apis=safe"
      - "--ws-origins=all"
      - "--no-ipc"
      - "--no-secretstore"
      - "--no-secretstore-http"
      - "--no-persistent-txqueue"
      - "--no-color"
      - "--tracing=off"
      - "--pruning=fast"
      - "--db-compaction=ssd"
    volumes:
      - type: bind
        source: /parity-ewc/
        target: /data
    restart: unless-stopped
    mem_limit: 12G
    mem_reservation: 16M
    stop_grace_period: 1m
    ports:
      - "8546:8545"
    networks:
      - net_rpc_external
      - dai_net_rpc_external
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net_rpc_external
      - dai_net_rpc_external
networks:
  net_rpc_external:
    external:
      name: bridge-common-network
  dai_net_rpc_external:
    external:
      name: dai-bridge-common-network
